# Generated by Django 6.0.4 on 2026-05-06 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrusionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('frame', 'Frame'), ('rail', 'Rail'), ('blade', 'Blade/Louvre'), ('track', 'Track'), ('compensating', 'Compensating'), ('rod', 'Rod'), ('hardware', 'Hardware')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('weight_per_mm', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('die_number', models.CharField(blank=True, max_length=50)),
                ('standard_bar_mm', models.PositiveIntegerField(default=6300)),
                ('kerf_mm', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('BAR', 'Bar (length)'), ('KG', 'Kilogram'), ('EACH', 'Each'), ('SET', 'Set')], default='BAR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.materialcategory')),
                ('extrusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.extrusiontype')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
