# Generated by Django 6.0.4 on 2026-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_colour_product_colour_code_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='default_markup_pct',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Default markup %% for products in this category', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Markup %% to apply instead of category default', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current selling price (auto or manual)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Last purchase cost price per unit', max_digits=12, null=True),
        ),
    ]
