# Generated by Django 6.0.4 on 2026-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_add_supplier_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
