# Generated by Django 6.0.4 on 2026-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_add_supplier_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
