# Generated by Django 6.0.4 on 2026-05-14 11:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('manufacturing', '0002_alter_job_options_job_priority'),
        ('products', '0003_phase_approval_and_invoice_flow'),
        ('purchasing', '0004_add_supplier_reg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_eft',
            field=models.BooleanField(default=False, help_text='True = EFT (POP required before ordering). False = on account.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='manufacturing.job'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='phase',
            field=models.CharField(choices=[('requisition', 'Requisition (Draft)'), ('pending_approval', 'Awaiting Approval'), ('approved', 'Approved — Ready to Send'), ('ordered', 'Sent to Supplier'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='requisition', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pop_document',
            field=models.FileField(blank=True, null=True, upload_to='purchasing/pop/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reason',
            field=models.CharField(blank=True, choices=[('stock_reorder', 'Stock Reorder (Minimum Reached)'), ('job_request', 'Job Request (Manufacturing)'), ('special_order', 'Special Order'), ('blanket', 'Blanket / Planned Order'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requires_quote',
            field=models.BooleanField(default=False, help_text='Send to supplier for pricing before placing order'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='manufacturing.job'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('supplier_inv_number', models.CharField(blank=True, help_text="Supplier's invoice reference", max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft (Entering)'), ('posted', 'Posted to Stock'), ('discrepancy', 'Discrepancy — Review Required')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('price_variance_json', models.JSONField(blank=True, default=dict)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.company')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.goodsreceivednote')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.purchaseorder')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoiced_qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_variance', models.DecimalField(decimal_places=2, default=0, help_text='Difference from PO unit price (+ = increase)', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='purchasing.purchaseorderline')),
            ],
            options={
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePriceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.company')),
                ('po_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='purchasing.purchaseorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='purchasing.supplier')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
