# Generated by Django 6.0.4 on 2026-05-07 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('division_type', models.CharField(choices=[('head_office', 'Head Office Division'), ('factory', 'Factory')], default='head_office', max_length=20)),
                ('factory_type', models.CharField(blank=True, choices=[('alu', 'Aluminium Shutter Factory'), ('fly', 'Flyscreen Factory'), ('wdw', 'Wood Factory')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.division')),
            ],
            options={
                'verbose_name_plural': 'Divisions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('location_type', models.CharField(choices=[('factory_section', 'Factory Section'), ('general_storage', 'General Storage'), ('offcut_storage', 'Offcut Storage'), ('store', 'Store'), ('office', 'Office'), ('staging', 'Staging Area'), ('quarantine', 'Quarantine'), ('shipping', 'Shipping'), ('receiving', 'Receiving'), ('powdercoat_in', 'Powder Coat In'), ('powdercoat_out', 'Powder Coat Out')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.division')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.location')),
            ],
            options={
                'ordering': ['division', 'name'],
                'unique_together': {('division', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='core.location')),
            ],
            options={
                'ordering': ['location', 'name'],
                'unique_together': {('location', 'name')},
            },
        ),
    ]
