# Generated by Django 6.0.4 on 2026-05-07 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutDesign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('job_no', models.CharField(blank=True, max_length=30)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('bar_plan_json', models.JSONField(blank=True, default=dict)),
                ('offcut_keep_min_mm', models.PositiveIntegerField(default=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('optimized', 'Optimized'), ('released', 'Released to Floor'), ('cut', 'Cuts Complete')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_designs', to='core.company')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_designs', to='core.division')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_designs', to='sales.salesorderline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CutBar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar_no', models.PositiveIntegerField(default=0)),
                ('stock_len_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kerf_mm', models.DecimalField(decimal_places=2, default=4, max_digits=8)),
                ('trim_start_mm', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ('trim_end_mm', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('offcut_mm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group_key', models.CharField(blank=True, max_length=200)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='cutting.cutdesign')),
            ],
            options={
                'ordering': ['design', 'bar_no'],
            },
        ),
        migrations.CreateModel(
            name='CutRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, max_length=30)),
                ('cut_length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('allocated_qty', models.PositiveIntegerField(default=0)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='cutting.cutdesign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['design', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CutBarCut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.PositiveIntegerField(default=0)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_lines', to='cutting.cutbar')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut_lines', to='cutting.cutrequirement')),
            ],
            options={
                'ordering': ['bar', 'position_mm'],
            },
        ),
        migrations.CreateModel(
            name='Offcut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_job_name', models.CharField(blank=True, max_length=200)),
                ('source_job_no', models.CharField(blank=True, max_length=30)),
                ('consumed_date', models.DateTimeField(blank=True, null=True)),
                ('extrusion', models.CharField(max_length=100)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, max_length=30)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_len_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_label', models.CharField(blank=True, max_length=100)),
                ('storage_area', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock / Available'), ('reserved', 'Reserved for Cut'), ('consumed', 'Consumed in Cut'), ('scrapped', 'Scrapped')], default='in_stock', max_length=20)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcut_record', to='cutting.cutbar')),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_offcuts', to='core.binlocation')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_offcuts', to='cutting.cutdesign')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcuts', to='cutting.cutdesign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cutbar',
            name='source_offcut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_as_source', to='cutting.offcut'),
        ),
        migrations.CreateModel(
            name='OffcutConsumeEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcut_consume_events', to='cutting.cutdesign')),
                ('offcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_events', to='cutting.offcut')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cutting.cutrequirement')),
            ],
            options={
                'ordering': ['offcut', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offcut',
            index=models.Index(fields=['extrusion', 'status'], name='cutting_off_extrusi_9a1d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='offcut',
            index=models.Index(fields=['status', 'length_mm'], name='cutting_off_status_340b1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cutbar',
            unique_together={('design', 'bar_no')},
        ),
    ]
