# Generated by Django 6.0.4 on 2026-05-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutdesign',
            name='company',
        ),
    ]
