# Generated by Django 6.0.4 on 2026-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0002_remove_cutdesign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutbar',
            name='is_flipped',
            field=models.BooleanField(default=False, help_text='Operator has placed this bar on the machine'),
        ),
        migrations.AddField(
            model_name='cutbarcut',
            name='is_cut',
            field=models.BooleanField(default=False),
        ),
    ]
