# Generated by Django 6.0.4 on 2026-05-06 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offcut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length_mm', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('finish', models.CharField(choices=[('mill', 'Mill'), ('powdercoated', 'Powdercoated')], default='mill', max_length=30)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offcuts', to='core.binlocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcuts', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offcuts', to='products.product')),
            ],
            options={
                'ordering': ['-length_mm'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ordered', 'On Order'), ('received', 'Received'), ('stored', 'In Store'), ('cut', 'Cut'), ('prepared', 'Prepared for Assembly'), ('sent_powder', 'Sent to Powder Coating'), ('returned_powder', 'Returned from Powder Coating'), ('assembled', 'Assembled'), ('cleaned', 'Cleaned'), ('packed', 'Packed'), ('installed', 'Installed'), ('consumed', 'Consumed'), ('discarded', 'Discarded')], default='stored', max_length=30)),
                ('requires_powdercoat', models.BooleanField(default=False)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_order', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='core.binlocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'state'], name='inventory_s_company_195248_idx'), models.Index(fields=['product', 'state'], name='inventory_s_product_8fa62b_idx')],
            },
        ),
    ]
