# Generated by Django 6.0.4 on 2026-05-06 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_key', models.CharField(max_length=200)),
                ('bars_used', models.PositiveIntegerField()),
                ('waste_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cut', 'Bars Cut'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['group_key'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('finish', models.CharField(choices=[('mill', 'Mill'), ('powdercoated', 'Powdercoated')], default='mill', max_length=30)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.bom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CutBar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_bar_id', models.CharField(blank=True, max_length=50)),
                ('bar_length_mm', models.PositiveIntegerField()),
                ('cuts_json', models.JSONField(default=list)),
                ('offcut_mm', models.PositiveIntegerField(default=0)),
                ('cut_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_bars', to='manufacturing.cutplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cutting', 'In Cutting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source_order', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'job_number')},
            },
        ),
        migrations.CreateModel(
            name='CutRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length_mm', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('finish', models.CharField(choices=[('mill', 'Mill'), ('powdercoated', 'Powdercoated')], default='mill', max_length=30)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('allow_offcut_match', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_requirements', to='products.product')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_requirements', to='manufacturing.job')),
            ],
            options={
                'ordering': ['product', 'length_mm'],
            },
        ),
        migrations.AddField(
            model_name='cutplan',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_plans', to='manufacturing.job'),
        ),
    ]
