# Generated by Django 6.0.4 on 2026-05-07 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cutting', '0002_remove_cutdesign_company'),
        ('products', '0002_product_colour_product_colour_code_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_number', models.PositiveIntegerField(help_text='Sequential number within this job (1, 2, 3...)')),
                ('name', models.CharField(blank=True, help_text="e.g. 'Opening 1 — Front Door' or 'Window A'", max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft — not yet final'), ('final', 'Final — sizes locked'), ('issued', 'Issued to Factory')], default='draft', max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('opening_type', models.CharField(choices=[('door', 'Door'), ('window', 'Window'), ('flyscreen', 'Flyscreen'), ('security', 'Security Barrier'), ('other', 'Other')], default='door', max_length=20)),
                ('WIDTH_MM', models.PositiveIntegerField(blank=True, help_text='Overall width (mm)', null=True)),
                ('HEIGHT_MM', models.PositiveIntegerField(blank=True, help_text='Overall height (mm)', null=True)),
                ('lock_type', models.CharField(blank=True, choices=[('none', 'No Lock'), ('standard', 'Standard Lock'), ('deadbolt', 'Deadbolt'), ('key', 'Key Operated'), ('thumb', 'Thumb Turn')], max_length=20)),
                ('colour_name', models.CharField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, max_length=30)),
                ('powder_coat', models.BooleanField(default=False, help_text='Requires powder coating')),
                ('mesh_type', models.CharField(choices=[('none', 'No Mesh'), ('fibreglass', 'Fibreglass'), ('aluminium', 'Aluminium'), ('security', 'Security Mesh')], default='none', max_length=20)),
                ('has_top_rail', models.BooleanField(default=True)),
                ('has_bottom_rail', models.BooleanField(default=True)),
                ('rail_width_mm', models.PositiveIntegerField(default=0)),
                ('hardware_notes', models.TextField(blank=True)),
                ('signed_off_by', models.CharField(blank=True, max_length=100)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['job', 'sheet_number'],
            },
        ),
        migrations.CreateModel(
            name='CutPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_key', models.CharField(max_length=200)),
                ('bars_used', models.PositiveIntegerField()),
                ('waste_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cut', 'Bars Cut'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['group_key'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('finish', models.CharField(choices=[('mill', 'Mill'), ('powdercoated', 'Powdercoated')], default='mill', max_length=30)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.bom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ControlSheetLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length_mm', models.PositiveIntegerField(blank=True, help_text='Override length (leave blank to use product standard)', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('finish', models.CharField(choices=[('mill', 'Mill (Uncoated)'), ('powdercoated', 'Powdercoated')], default='mill', max_length=30)),
                ('powder_color', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, choices=[('left', 'Left Stile'), ('right', 'Right Stile'), ('top', 'Top Rail'), ('bottom', 'Bottom Rail'), ('mid', 'Mid Rail'), ('louvre', 'Louvre'), ('track', 'Track'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('control_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.controlsheet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_sheet_lines', to='products.product')),
            ],
            options={
                'ordering': ['position', 'product'],
            },
        ),
        migrations.CreateModel(
            name='CutPlanBar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_bar_id', models.CharField(blank=True, max_length=50)),
                ('bar_length_mm', models.PositiveIntegerField()),
                ('cuts_json', models.JSONField(default=list)),
                ('offcut_mm', models.PositiveIntegerField(default=0)),
                ('cut_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='manufacturing.cutplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed — awaiting final sizes'), ('ready', 'Ready — all control sheets in, ready for cut'), ('cutting', 'In Cutting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
                ('cut_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_jobs', to='cutting.cutdesign')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_jobs', to='core.division')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CutRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cut_length_mm', models.PositiveIntegerField(help_text='Finished cut length (after all processing)')),
                ('qty', models.PositiveIntegerField()),
                ('style', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, max_length=30)),
                ('allow_offcut_match', models.BooleanField(default=True)),
                ('allocated_qty', models.PositiveIntegerField(default=0)),
                ('control_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_requirements', to='manufacturing.controlsheet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_requirements', to='products.product')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_requirements', to='manufacturing.job')),
            ],
            options={
                'ordering': ['product', 'cut_length_mm'],
            },
        ),
        migrations.AddField(
            model_name='cutplan',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_plans', to='manufacturing.job'),
        ),
        migrations.AddField(
            model_name='controlsheet',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_sheets', to='manufacturing.job'),
        ),
        migrations.AlterUniqueTogether(
            name='controlsheet',
            unique_together={('job', 'sheet_number')},
        ),
    ]
