# Generated by Django 6.0.4 on 2026-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
