# Generated by Django 6.0.4 on 2026-05-07 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowdercoatSupplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('lead_time_days', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PowdercoatJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=20, unique=True)),
                ('powder_color', models.CharField(max_length=100)),
                ('powder_color_code', models.CharField(blank=True, max_length=30)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — not yet sent'), ('sent', 'Sent to Powder Coater'), ('returned', 'Returned from Powder Coater'), ('completed', 'Completed — all items received back'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powdercoat_jobs', to='core.division')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powdercoat_jobs', to='powdercoat.powdercoatsupplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowdercoatJobItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extrusion', models.CharField(max_length=100)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('length_mm', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sent_state', models.CharField(max_length=30)),
                ('returned_state', models.CharField(blank=True, max_length=30)),
                ('qc_result', models.CharField(choices=[('pass', 'Pass'), ('conditional', 'Conditional'), ('fail', 'Fail'), ('pending', 'Pending Inspection')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='powdercoat.powdercoatjob')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powdercoat_items', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['job', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('incoming_grn', 'Incoming (GRN)'), ('issue_factory', 'Issue to Factory'), ('outgoing_powder', 'Outgoing to Powder Coating'), ('incoming_powder', 'Returning from Powder Coating'), ('pre_cut', 'Pre-Cut Check'), ('final_qc', 'Final QC')], max_length=30)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('conditional', 'Conditional — note issue'), ('fail', 'Fail — reject')], max_length=20)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('fail_reason', models.CharField(blank=True, max_length=50)),
                ('condition', models.TextField(blank=True)),
                ('powdercoat_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='powdercoat.powdercoatjob')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='inventory.stockitem')),
            ],
            options={
                'verbose_name_plural': 'Quality Checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued to Factory'), ('confirmed', 'Confirmed at Factory'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='core.division')),
                ('receiving_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues_received', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIssueLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('extrusion', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, max_length=30)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('qc_result', models.CharField(choices=[('pass', 'Pass'), ('conditional', 'Conditional'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('qc_notes', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='powdercoat.stockissue')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['issue', 'id'],
            },
        ),
    ]
